name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'images/**'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['datascience', 'deeplearning']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: images/${{ matrix.image }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max