name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'requirements.txt'
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 首先登录到阿里云容器镜像服务
      # 然后登录到 GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/datascience:latest
            ghcr.io/${{ github.repository_owner }}/datascience:${{ steps.date.outputs.date }}
            registry.cn-hangzhou.aliyuncs.com/swufelab/datascience:latest
            registry.cn-hangzhou.aliyuncs.com/swufelab/datascience:${{ steps.date.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max