name: Test Requirements Installation

on:
  push:
    paths:
      - 'requirements.txt'
  pull_request:
    paths:
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  test-requirements:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyterlab==4.1.2 jupyter-server-proxy==4.1.2

    - name: Test imports
      run: |
        python -c "import numpy; import pandas; import matplotlib; import sklearn"
        python -c "import jupyterlab"
